---
# tasks file for ownca-setup

- name: Create PKI file hierarchy
  block:
    - name: Create PKI directory
      ansible.builtin.file:
        path: "/etc/pki/CA"
        state: directory
        mode: '0755'

    - name: Create PKI directories
      ansible.builtin.file: 
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "/etc/pki/CA/certs"
        - "/etc/pki/CA/private"
        - "/etc/pki/CA/crl"
        - "/etc/pki/CA/requests"
        - "/etc/pki/CA/newcerts"
        - "/etc/pki/CA/serial"

    - name: Create Database and CRL number files
      ansible.builtin.file:
        path: "{{ item }}"
        state: touch
        mode: '0644'
      with_items:
        - "/etc/pki/CA/index.txt"
        - "/etc/pki/CA/crlnumber"
        - "/etc/pki/CA/serial"

    - name: Add number to crlnumber file
      ansible.builtin.lineinfile:
        line: "1000"
        path: "/etc/pki/CA/crlnumber"

    - name: Add number to serial file
      ansible.builtin.lineinfile:
        line: "1000"
        path: "/etc/pki/CA/serial"

  become: yes

- name: Write CA configuration file
  ansible.builtin.template:
    src: ca.conf.j2
    dest: "/etc/pki/CA/ca.conf"
    mode: "0644"
  become: yes
