---
# tasks file for ra-setup
- name: Install dependencies
  block:
    - name: Install ansible
      ansible.builtin.package:
        name: ansible
        state: present

    - name: Install Python 3
      ansible.builtin.package:
        name: python3
        state: present

    - name: Install PIP 3
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install PyYAML
      ansible.builtin.pip:
        name: pyyaml

    - name: Install Ansible Runner
      ansible.builtin.pip:
        name: ansible-runner

    - name: Install pexpect
      ansible.builtin.pip:
        name: pexpect

    - name: Install sshpass program
      ansible.builtin.package:
        name: sshpass
        state: present

  become: yes

- name: Clone this repo
  ansible.builtin.git:
    repo: "https://github.com/N3L-s0n/own-certificate-authority.git" 
    dest: "~/registration-authority"
    clone: yes
    version: "pki-vpn"

- name: Copy inventory file
  ansible.builtin.copy:
    src: "inventory"
    dest: "~/registration-authority/playbooks/inventory"

- name: Create RA directories
  block:
    - name: Create KEYS directory
      ansible.builtin.file:
        path: "/etc/pki/RA/"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Create KEYS directory
      ansible.builtin.file:
        path: "/etc/pki/RA/private"
        state: directory
        mode: '0755'

    - name: Create CSR directory
      ansible.builtin.file:
        path: "/etc/pki/RA/csr"
        state: directory
        mode: '0755'

    - name: Create PKCS#12 directory
      ansible.builtin.file:
        path: "/etc/pki/RA/pkcs12"
        state: directory
        mode: '0755'
  become: yes
