---
- name: Create private key for new certificate
  community.crypto.openssl_privatekey:
    path: "{{ dir_key }}/{{ common_name }}.key"
    passphrase: "{{ priv_passphrase }}"
    cipher: auto
    size: 4096
    type: RSA
  become: yes

- name: Create server certificate signing request (CSR)
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ dir_key }}/{{ common_name }}.key"
    privatekey_passphrase: "{{ priv_passphrase }}"

    country_name: "{{ request_info.country_name }}"
    state_or_province_name: "{{ request_info.state_or_province_name }}"
    locality_name: "{{ request_info.locality_name }}"
    organization_name: "{{ request_info.organization_name }}"
    organizational_unit_name: "{{ request_info.organizational_unit_name }}"
    common_name: "{{ request_info.common_name }}"

    basic_constraints: "{{ request_info.basic_constraints.data}}"
    basic_constraints_critical: "{{ request_info.basic_constraints.critical }}"

    key_usage: "{{ request_info.key_usage.data }}"
    key_usage_critical: "{{ request_info.key_usage.critical }}"

    subject_alt_name: "{{ request_info.subject_alt_name.data }}"
    subject_alt_name_critical: "{{ request_info.subject_alt_name.critical }}"

    crl_distribution_points: "{{ request_info.crl_distribution_points }}"

  register: server_csr
  become: yes

- name: Store CSR file created
  ansible.builtin.copy:
    content: "{{ server_csr.csr }}"
    dest: "{{ dir_csr }}/{{ common_name }}.csr"
  become: yes

- name: Get CSR file in control node
  ansible.builtin.copy:
    content: "{{ server_csr.csr }}"
    dest: /tmp/{{ common_name }}.csr
  delegate_to: 127.0.0.1
