---
- name: Create private key for new certificate
  community.crypto.openssl_privatekey:
    path: "/etc/pki/CA/private/{{ request.name }}.key"
    passphrase: "{{ priv_passphrase }}"
    cipher: auto
    size: 4096
    type: RSA
  become: yes

- name: Create server certificate signing request (CSR)
  community.crypto.openssl_csr_pipe:
    privatekey_path: "/etc/pki/CA/private/{{ request.name }}.key"
    privatekey_passphrase: "{{ priv_passphrase }}"

    country_name: "{{ request.data.country_name }}"
    state_or_province_name: "{{ request.data.state_or_province_name }}"
    locality_name: "{{ request.data.locality_name }}"
    organization_name: "{{ request.data.organization_name }}"
    organizational_unit_name: "{{ request.data.organizational_unit_name }}"
    common_name: "{{ request.data.common_name }}"

    basic_constraints: "{{ request.data.basic_constraints.data}}"
    basic_constraints_critical: "{{ request.data.basic_constraints.critical }}"

    key_usage: "{{ request.data.key_usage.data }}"
    key_usage_critical: "{{ request.data.key_usage.critical }}"

    subject_alt_name: "{{ request.data.subject_alt_name.data }}"
    subject_alt_name_critical: "{{ request.data.subject_alt_name.critical }}"

    crl_distribution_points: "{{ request.data.crl_distribution_points }}"

  register: client_csr
  become: yes

- name: Store CSR file created
  ansible.builtin.copy:
    content: "{{ client_csr.csr }}"
    dest: "/etc/pki/CA/certs/{{ request.name }}.csr"
  become: yes

- name: Get CSR file in control node
  ansible.builtin.copy:
    content: "{{ client_csr.csr }}"
    dest: /tmp/{{ request.name }}.csr
  delegate_to: 127.0.0.1
