---
- hosts: all

# This playbook run all setup needed to use community.crypto 2.3.2 if using default variables
  roles:
    - role: openssl-install
    - role: python3-install
    - role: ansible-install
      tags: [ local ]
    - role: cryptography-install

  post_tasks:
    - name: Install pexpect
      ansible.builtin.pip:
        name: pexpect
        executable: pip3.10
        extra_args: --user

    - name: Refresh table of recently executed programs
      ansible.builtin.shell:
        cmd: hash -r
      tags:
        - local

    - name: Install Softhsm v2
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - softhsm
        - opensc
        - gnutls-utils
        - openssl-pkcs11
      become: yes

    - name: Remove old Ansible yum installation
      ansible.builtin.yum:
        name: ansible
        state: absent
      become: yes
      tags:
        - local
