---
- hosts: issuers
  vars_prompt:
    - name: priv_passphrase
      prompt: "\n# PRIVATE KEY PASSPHRASE\n Enter key passphrase"
      private: yes

    - name: priv_passphrase_confirmation
      prompt: " Enter same key passphrase for confirmation"
      private: yes

  pre_tasks:
    - name: Check if passphrases are equal
      ansible.builtin.fail:
        msg: "Key passphrase and confirmation differ"
      when: priv_passphrase != priv_passphrase_confirmation

  roles:
    - role: ownca-setup
      tags:
        - never
    - role: certificate-request
      when: hostvars[inventory_hostname]['request'] is defined
