---
- hosts: clients
  roles:
    - role: certificate-request # registers new CSR

  post_tasks:
    - name: Save CSR in client
      ansible.builtin.copy:
        content: "{{ client_csr.csr }}"
        dest: /home/{{ ansible_user }}/{{ request.name }}.csr.pem
      become: yes

- hosts: issuer
  tasks:
    - name: Print CSR data
      ansible.builtin.debug:
        msg: "{{ hostvars[groups.clients[0]]['client_csr'].csr }}"

    - name: Sign certificate signing request (CSR)
      block:
        - name: Sign with CA certificate
          community.crypto.x509_certificate_pipe:
            csr_content: "{{ hostvars[groups.clients[0]]['client_csr'].csr }}"
            ownca_path: /etc/pki/CA/certs/{{ ca_name }}.cert.pem
            ownca_privatekey_path: /etc/pki/CA/private/{{ ca_name }}.key
            ownca_privatekey_passphrase: "{{ ca_passphrase }}"

            ownca_not_after: "+{{ time | default('365') }}d"
            ownca_not_before: "-1d"

            provider: ownca
          register: cert
          become: yes

        - name: Save certificate result
          ansible.builtin.set_fact:
            cert_result: "{{ cert }}"
            cacheable: yes

        - name: Save signed certificate in client
          ansible.builtin.copy:
            content: "{{ cert.certificate }}"
            dest: /home/{{ ansible_user }}/{{ request.name }}.cert.pem
          delegate_to: "{{ groups.clients[0] }}"

        - name: Save signed certificate in CA
          ansible.builtin.copy:
            content: "{{ cert.certificate }}"
            dest: /etc/pki/CA/requests/{{ request.name }}.cert.pem
          become: yes
